version: "2.4"

services:
  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./nginx/src/data
        target: /usr/share/nginx/html
    depends_on: 
      - php-fpm
    networks:
      net:
        ipv4_address: 172.16.1.2 
  
  php-fpm:
    image: php74-fpm
    build: ./php-fpm
    container_name: php74-fpm
    volumes:
      - type: bind
        source: ./nginx/src/data
        target: /usr/share/nginx/html
    networks:
      net:
        ipv4_address: 172.16.1.3

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
